### ISSUE TITLE
need to update to 3.1.10 to fix security issue

### ISSUE THREAD

**Issue by ferndopolis** [michaelkirk/household-account-mgmt#5]
read more here 
http://weblog.rubyonrails.org/2013/1/8/Rails-3-2-11-3-1-10-3-0-19-and-2-3-15-have-been-released/

**Comment by michaelkirk** [comment]
Oh don't you worry, I've heard all about it ;).

I'm going to make a go at updating it right now, if it doens't got
smoothly, maybe we can take a look later this afternoon?

M
